window.PLAYLISTS = [
  {
    "id": "pl-1cdba83376",
    "title": "CI for ESL Beginners",
    "url": "https://youtube.com/playlist?list=PLqE81DRO-TpFUby7iTm_7M7NWVyze4B82&si=3MfgJvC_4hGlXCwx",
    "level": "A1",
    "durationHours": 62,
    "videoCount": 159,
    "accent": "Canadian",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-bf65d95714",
    "title": "ComprehensibleInputAus",
    "url": "https://youtube.com/playlist?list=PLPCDGFknL8Ov6xPycL0vONH-1_s_JHVVO&si=wN9KH3DyXLqlmX7R",
    "level": "A1",
    "durationHours": 17,
    "videoCount": 90,
    "accent": "Australian",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-4266a4ef4f",
    "title": "Acquirable English",
    "url": "https://youtube.com/playlist?list=PL_pzbjRF59WSGECU7r0AmNjKxIHtUheJa&si=wmexsVs0USY_aGV7",
    "level": "A1",
    "durationHours": 14,
    "videoCount": 34,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-13b74c13ec",
    "title": "English with Beth",
    "url": "https://youtube.com/playlist?list=PLoQjhQuO0mXktEK_Cbemz2x19chABBTaO&si=ay6stP8ussTIT8tO",
    "level": "A1",
    "durationHours": 15,
    "videoCount": 40,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-eb3e9B1-B2575",
    "title": "Isaac Cloward 1",
    "url": "https://youtube.com/playlist?list=PLKt7dWUJknRh6xHI-K-0l5ZsQXT1dcKck&si=lW9tlgbtKIu86p3F",
    "level": "A1",
    "durationHours": 11,
    "videoCount": 52,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-7576b69083",
    "title": "Fingtam English",
    "url": "https://youtube.com/playlist?list=PL5QKY42gcQznpXyB23HSy_JTvKNvGjKa7&si=PwxUKl51VHUThJQO",
    "level": "A1",
    "durationHours": 10,
    "videoCount": 69,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-862fa26204",
    "title": "Miss Honey",
    "url": "https://youtube.com/playlist?list=PL8f0I_2tet-fDkhrcr6oXRK75kY6sxJWH&si=wpmGfL_wnVy9ATld",
    "level": "A1",
    "durationHours": 12,
    "videoCount": 43,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-399a072bc0",
    "title": "Acquirable English",
    "url": "https://youtube.com/playlist?list=PL_pzbjRF59WRhWycx2Uapa-2v4cTDU05x&si=GjQZg6pACY1LqmGz",
    "level": "A1",
    "durationHours": 6,
    "videoCount": 31,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-7751cacd4e",
    "title": "EnglishSponge",
    "url": "https://youtube.com/playlist?list=PLI7Ex3Iy2Ewqo0EnHUwhE5sxiFWBRyUAk&si=kURPj1rs-5SRYy4i",
    "level": "A1",
    "durationHours": 5,
    "videoCount": 40,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-3d3dd33f22",
    "title": "English Acquired",
    "url": "https://youtube.com/playlist?list=PLOu7BsKh86SM_o6I92FT7ySePzO32jn8s&si=TWCzkWNFQEh1GnyV",
    "level": "A1",
    "durationHours": 3,
    "videoCount": 10,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-1ae213637b",
    "title": "English Input",
    "url": "https://youtube.com/playlist?list=PLmB90xqDKIbgkiEw8nEhgPTtjKG1tlJY8&si=RLmDZHU3LNPCUOA9",
    "level": "A1",
    "durationHours": 3,
    "videoCount": 24,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-a270e34be4",
    "title": "English Fiesta",
    "url": "https://www.youtube.com/playlist?list=PLi0W0eZGtsDVqcaoXGhVrDuvkocngaq8e",
    "level": "A1",
    "durationHours": 3,
    "videoCount": 26,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-54c35c6821",
    "title": "English without Fear",
    "url": "https://www.youtube.com/playlist?list=PLKxFPyhwH5ahhU1lQyW9ge2P581_6jhD3",
    "level": "A1",
    "durationHours": 2,
    "videoCount": 15,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-0aa0d7625d",
    "title": "English Stories for Ana",
    "url": "https://youtube.com/playlist?list=PLCpH9_Zu6kFrZTod1WfLkiSAh2KmKhTPE&si=m_yS6VuJNbWMH_3H",
    "level": "A1",
    "durationHours": 3,
    "videoCount": 30,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-b6adf46408",
    "title": "Ben's Language Lab",
    "url": "https://youtube.com/playlist?list=PL7yrVR1epvJokOdOJx9jMf-wf2Cf4G5sO&si=xxGd3ZrE6rvYxnpI",
    "level": "A1",
    "durationHours": 1,
    "videoCount": 4,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-22cc08a35d",
    "title": "Wicked Good English",
    "url": "https://www.youtube.com/playlist?list=PLSBUgMc0ndGdmG9llZZRNpNUayBoaaK9M",
    "level": "A1",
    "durationHours": 1,
    "videoCount": 6,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-5972b0fb3b",
    "title": "Miss Jean Teacher",
    "url": "https://youtube.com/playlist?list=PLrr_7ZHoCB20vwtFQu3xA4fASgQiSQ0Aj&si=hnLBpfHO8MnbqEDb",
    "level": "A1",
    "durationHours": 1,
    "videoCount": 9,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-22f9568af1",
    "title": "Not your Mother's English",
    "url": "https://youtube.com/playlist?list=PLMkT-IVAR40lIqrQ7ay4S06Ou4NQbxCfC&si=NQa0heh__E6tMdxB",
    "level": "A1",
    "durationHours": 0,
    "videoCount": 3,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-06e6e0174d",
    "title": "English from the Ground Up",
    "url": "https://youtube.com/playlist?list=PLEeZEYCefqthVEbvWh4be-OzTNgmB5iVS&si=1Xg4BG68eGKe8wfi",
    "level": "A2",
    "durationHours": 17,
    "videoCount": 50,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-806561b393",
    "title": "English Acquired",
    "url": "https://youtube.com/playlist?list=PLOu7BsKh86SPC5_a1zRYKecss0OAa13wL&si=iOoPyHtrQsriC7IA",
    "level": "A2",
    "durationHours": 15,
    "videoCount": 65,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-a8bf78c6ea",
    "title": "Dreaming English",
    "url": "https://www.youtube.com/playlist?list=PL_G1fdUGuZUFxUopJJ29s0hsMszOp708q",
    "level": "A2",
    "durationHours": 12,
    "videoCount": 80,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-e433dB1-B248c",
    "title": "English on Autopilot",
    "url": "https://youtube.com/playlist?list=PLUCskyzT0rc7EmzJ2rlDCe7laTf7lLWmb&si=JyYihy5j9UjrNLou",
    "level": "A2",
    "durationHours": 11,
    "videoCount": 58,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-8041f3c8dd",
    "title": "Eng Comprehensible Input",
    "url": "https://youtube.com/playlist?list=PL95nNa6WM9n8EZ0xOVH1jCAFGHQtyphRS&si=ObRP4Qu30-jGbfHv",
    "level": "A2",
    "durationHours": 10,
    "videoCount": 38,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-7f0d73b90f",
    "title": "English Cozy Chat",
    "url": "https://youtube.com/playlist?list=PLpm1IJUtg25dkjdc6VsbYGogO5Qh287On&si=Z0ZMxM6XebDIK2U1",
    "level": "A2",
    "durationHours": 14,
    "videoCount": 58,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-e1e0f97a19",
    "title": "EnglishSponge",
    "url": "https://youtube.com/playlist?list=PLI7Ex3Iy2EwrVaktQ6xb_mUtrf2ZOpFRB&si=ObZOfTbwYH8SZxZ7",
    "level": "A2",
    "durationHours": 8,
    "videoCount": 52,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-29a0c5021e",
    "title": "ComprehensibleInputAus",
    "url": "https://youtube.com/playlist?list=PLPCDGFknL8OvULYrFnZF6tEXJeToMbF8H&si=BEh3mPm9oV42u8VP",
    "level": "A2",
    "durationHours": 5,
    "videoCount": 24,
    "accent": "Australian",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-4326ee6d2d",
    "title": "English Stories for Ana",
    "url": "https://youtube.com/playlist?list=PLCpH9_Zu6kFrHi83dG9sKJ3FgQhdfHgcV&si=NeS2X75U4boep0n5",
    "level": "A2",
    "durationHours": 13,
    "videoCount": 85,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-f797fff8a1",
    "title": "English without Fear",
    "url": "https://www.youtube.com/playlist?list=PLKxFPyhwH5ahaMVf0Ymw5Hn7azYVjlJ7K",
    "level": "A2",
    "durationHours": 5,
    "videoCount": 35,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-63a82dcf0a",
    "title": "English after hours",
    "url": "https://youtube.com/playlist?list=PLFwYbY3wHtZP9nHnu8fbqLPo-2Tte3taT&si=Pu4YzaDbhZiTgdpg",
    "level": "A2",
    "durationHours": 5,
    "videoCount": 29,
    "accent": "Irish",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-8d6a960558",
    "title": "Image Talk",
    "url": "https://youtube.com/playlist?list=PL7yrVR1epvJrcMgqJWhgWHz0NgM8qGb7Z&si=qQttYPLGZgSfpZU1",
    "level": "A2",
    "durationHours": 4,
    "videoCount": 12,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-b6be91d6d9",
    "title": "Isaac Cloward",
    "url": "https://youtube.com/playlist?list=PLKt7dWUJknRjsvdDScVjIvgID23GnWtFe&si=ZKZbtkc95H3cJuge",
    "level": "A2",
    "durationHours": 4,
    "videoCount": 21,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-fb4dd38fb0",
    "title": "Dreaming English",
    "url": "https://www.youtube.com/playlist?list=PL_G1fdUGuZUHb_rVHycrwmJ1bRaJrUbhm",
    "level": "A2",
    "durationHours": 3,
    "videoCount": 18,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-3582e0cfbf",
    "title": "English Acquired (Comic Books)",
    "url": "https://youtube.com/playlist?list=PLOu7BsKh86SNP4J6oi3yuyL9xwHMKfYY0&si=lwv8vjSwn3jT4npp",
    "level": "A2",
    "durationHours": 3,
    "videoCount": 7,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-1bd170cf5a",
    "title": "Acquirable English",
    "url": "https://youtube.com/playlist?list=PL_pzbjRF59WQ3MBq6WzKo-WpGLRWOcm53&si=EPvSoD_bNEo0e8CM",
    "level": "A2",
    "durationHours": 2,
    "videoCount": 6,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-dcc3271c7d",
    "title": "Not your Mother's English",
    "url": "https://youtube.com/playlist?list=PLMkT-IVAR40mOsawKntbAo-brF9kR3TqH&si=69swslS148sHxheo",
    "level": "A2",
    "durationHours": 1,
    "videoCount": 7,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-97e6531d5b",
    "title": "Wicked Good English",
    "url": "https://www.youtube.com/playlist?list=PLSBUgMc0ndGepTF1h588I0DY7cW1EuIw0",
    "level": "A2",
    "durationHours": 1,
    "videoCount": 6,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-a498a3c0e4",
    "title": "English Acquired (minecraft)",
    "url": "https://youtube.com/playlist?list=PLOu7BsKh86SOlVmhMUUpr1THnHYLkrNbq&si=4sxS_nqm67znB5Ut",
    "level": "B1-B2",
    "durationHours": 65,
    "videoCount": 55,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-a7629561c5",
    "title": "American English",
    "url": "https://www.youtube.com/playlist?list=PLrnzBkCm2eoyNjt-u0qEYnuF3VWiwAFay",
    "level": "B1-B2",
    "durationHours": 50,
    "videoCount": 387,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": null
  },
  {
    "id": "pl-19a00ee204",
    "title": "Easy English",
    "url": "https://youtube.com/playlist?list=PLu1As8p-8QYdNtEdxj5bgAW451FEgFvH4&si=nikkV6z_fZu2Y4hd",
    "level": "B1-B2",
    "durationHours": 46,
    "videoCount": 168,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": null
  },
  {
    "id": "pl-6f2dab376c",
    "title": "Dreaming English",
    "url": "https://www.youtube.com/playlist?list=PL_G1fdUGuZUHsyCKVpoMSaskFj3ZYUKkw",
    "level": "B1-B2",
    "durationHours": 33,
    "videoCount": 161,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-13eeb79756",
    "title": "Pensando Ingles",
    "url": "https://youtube.com/playlist?list=PL9R7Y14jiOgr-bmnn1ycmckam3nkkPm-Z&si=7S9xK5Jg1CK10KBW",
    "level": "B1-B2",
    "durationHours": 36,
    "videoCount": 97,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-087b3c4bee",
    "title": "EnglishSponge (B1-B2)",
    "url": "https://youtube.com/playlist?list=PLI7Ex3Iy2EwqOGOF2aRoP-eMUNJ2U6u_x&si=8YZm363PUAgpfOga",
    "level": "B1-B2",
    "durationHours": 32,
    "videoCount": 140,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-05f7e5af2b",
    "title": "Bo’s Slow English",
    "url": "https://youtube.com/playlist?list=PL1Vvf9gFRkYdo_IkFcuVyjk3WzdyVpbOK&si=G3SYNeHZqhPJvOCC",
    "level": "B1-B2",
    "durationHours": 35,
    "videoCount": 127,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-0aeee3aB1-B2c",
    "title": "English with Gemma",
    "url": "https://youtube.com/playlist?list=PLcPAwtW6mYOgUzt3VdiZ0dmBhe9uYx2mw&si=D_77cBsp7iFEK2c_",
    "level": "B1-B2",
    "durationHours": 26,
    "videoCount": 82,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": null
  },
  {
    "id": "pl-a93c867B1-B24",
    "title": "English without Fear",
    "url": "https://youtube.com/playlist?list=PLKxFPyhwH5ag_fw3Jo49UzVmh8U4ma5jz&si=siv9Rww81hIMhTPd",
    "level": "B1-B2",
    "durationHours": 23,
    "videoCount": 153,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-91991cd022",
    "title": "English Coach 3Ts",
    "url": "https://youtube.com/playlist?list=PLAQnGJZE3wfzxBphiKX6NF2Z4yD_3xQeC&si=YX4izXWdU-CyVCsw",
    "level": "B1-B2",
    "durationHours": 24,
    "videoCount": 95,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-1ba4f9962d",
    "title": "Ariannita la Gringa",
    "url": "https://youtube.com/playlist?list=PL50GkV3cQyq7MzhHP2R-9H84p-cUrYskQ&si=EL2mDxW94h8d7kfJ",
    "level": "B1-B2",
    "durationHours": 24,
    "videoCount": 83,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-9a021920b5",
    "title": "Miss Jean Teacher",
    "url": "https://www.youtube.com/playlist?list=PLrr_7ZHoCB21m0qihN_mZEw4MRh-0Spcv",
    "level": "B1-B2",
    "durationHours": 20,
    "videoCount": 91,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": null
  },
  {
    "id": "pl-7408dcc074",
    "title": "English with Teacher Levi",
    "url": "https://youtube.com/playlist?list=PL_GLmQYdj60fxFKKYUEVuUsi6FbJOPxxM&si=FWEtGn9vxMEe1nC_",
    "level": "B1-B2",
    "durationHours": 21,
    "videoCount": 64,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-819bcd7861",
    "title": "English at Ease",
    "url": "https://youtube.com/@englishatease-s4r?si=6RDTYdY73TWCnBv1",
    "level": "B1-B2",
    "durationHours": 22,
    "videoCount": 85,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-9cf5fe0c73",
    "title": "Learn English with Camille",
    "url": "https://www.youtube.com/playlist?list=PLJ5qkOTqBd8Hs1T6tRWpVVhuvF1MLz84S",
    "level": "B1-B2",
    "durationHours": 17,
    "videoCount": 76,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-a01205a644",
    "title": "Mad English TV (English Cooking)",
    "url": "https://youtube.com/playlist?list=PL2-SI2qqn8uRYPCmCXR6urvLzGx5ksE92&si=tIeY9hun8097GAjw",
    "level": "B1-B2",
    "durationHours": 17,
    "videoCount": 35,
    "accent": "Canadian",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-03ee87aca4",
    "title": "English Stories for Ana",
    "url": "https://youtube.com/playlist?list=PLCpH9_Zu6kFqNLbEw1moWLFb5zjOTA-i5&si=LumPtVQhw__C8bbD",
    "level": "B1-B2",
    "durationHours": 12,
    "videoCount": 129,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-f42fdde94a",
    "title": "The Forest",
    "url": "https://youtube.com/playlist?list=PLOu7BsKh86SNiIOsXdvULvrAnCNMk9skJ&si=ooYgpwF50nc91Bmf",
    "level": "B1-B2",
    "durationHours": 14,
    "videoCount": 14,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-B1-B2353B1-B250f",
    "title": "English on Autopilot",
    "url": "https://youtube.com/playlist?list=PLUCskyzT0rc6E1EPpgo4BL1xjUpL9Fso9&si=WNVIeD20krfVrtbj",
    "level": "B1-B2",
    "durationHours": 13,
    "videoCount": 61,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-44a2972f3e",
    "title": "Mad English TV (Road Trip Across Canada)",
    "url": "https://youtube.com/playlist?list=PL2-SI2qqn8uTbKL63_e61-jAyC-zqbk3h&si=vCnZ07BHXEl-fpj3",
    "level": "B1-B2",
    "durationHours": 12,
    "videoCount": 32,
    "accent": "Canadian",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-a7a00852c5",
    "title": "EnglishSponge",
    "url": "https://youtube.com/playlist?list=PLI7Ex3Iy2Ewo_m072OKy17ykaLK9D_LXE&si=bEJkb64uUcEzFDqz",
    "level": "B1-B2",
    "durationHours": 11,
    "videoCount": 48,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-11adc9c1a3",
    "title": "Stardew Valley",
    "url": "https://youtube.com/playlist?list=PLOu7BsKh86SPCjbwNih4EMgSkLGOTTuNG&si=fb2l-ffeI1fFaeib",
    "level": "B1-B2",
    "durationHours": 10,
    "videoCount": 10,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-589a6c2e32",
    "title": "Minecraft B1-B2",
    "url": "https://youtube.com/playlist?list=PLOu7BsKh86SPdsEAzCnlYdunZgdGcbxbA&si=HxiKbGkwByq4PMCW",
    "level": "B1-B2",
    "durationHours": 10,
    "videoCount": 10,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-064ebce4cd",
    "title": "Learn English with Camille",
    "url": "https://youtube.com/playlist?list=PLJ5qkOTqBd8GFfyX1mC8_oY4bAw7bom2V&si=UJ9zDyZnDR0P3h4n",
    "level": "B1-B2",
    "durationHours": 9,
    "videoCount": 40,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-073b067cb7",
    "title": "Slow English With Brian",
    "url": "https://www.youtube.com/playlist?list=PL_m_LH-e5q4hAnEvS6d9mAlgsvNYCIfGy",
    "level": "B1-B2",
    "durationHours": 8,
    "videoCount": 42,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": null
  },
  {
    "id": "pl-80438255e4",
    "title": "English by Jay",
    "url": "https://youtube.com/playlist?list=PLN10fSyMzgEwh5GDzH2IkBJ0rUHfcqiTH&si=9EfRSDFwbZmSGkMg",
    "level": "B1-B2",
    "durationHours": 10,
    "videoCount": 36,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-beb7b8f886",
    "title": "Bumbling Around in English",
    "url": "https://www.youtube.com/@bumblingaroundinenglish/videos",
    "level": "B1-B2",
    "durationHours": 8,
    "videoCount": 8,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-892687c399",
    "title": "Everyday American English",
    "url": "https://youtube.com/playlist?list=PLpBN9DfjoACnYwnURU-YJnmXx14T8HLIs&si=5nARlifES2ay32ww",
    "level": "B1-B2",
    "durationHours": 8,
    "videoCount": 30,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-f9fe5c6428",
    "title": "English Stories for Ana (B1-B2)",
    "url": "https://youtube.com/playlist?list=PLCpH9_Zu6kFrprL0dfOkpMFe3dWZ66bet&si=WO2Phz-ZR1U_v86Q",
    "level": "B1-B2",
    "durationHours": 11,
    "videoCount": 59,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-873a340ea7",
    "title": "Learn English with Benji",
    "url": "https://youtube.com/playlist?list=PLGGF07yfo4CyGboseu6LaKAdhmWmxhf7t&si=QIRKRg9PLVIUI92G",
    "level": "B1-B2",
    "durationHours": 9,
    "videoCount": 57,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-cd91c54095",
    "title": "UK and Ireland in English",
    "url": "https://www.youtube.com/playlist?list=PL0J8XtnnCuEPgUOYZCW3wrM_ry4vy-GMI",
    "level": "B1-B2",
    "durationHours": 7,
    "videoCount": 25,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-7650bf4363",
    "title": "How to do something",
    "url": "https://youtube.com/playlist?list=PLKxFPyhwH5aj2w03ZrF03gZNphh5wwBIT&si=Stmmc5N4M2-bUG1p",
    "level": "B1-B2",
    "durationHours": 7,
    "videoCount": 42,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-90b512debc",
    "title": "The Last Campfire",
    "url": "https://www.youtube.com/playlist?list=PLrVTvsIgrqL2gwMOoscKsR9CSy5HZpzuT",
    "level": "B1-B2",
    "durationHours": 7,
    "videoCount": 9,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-06b9ed507b",
    "title": "English After Hours",
    "url": "https://youtube.com/playlist?list=PLFwYbY3wHtZP0np9mV0jO7j7wtzpnnKB-&si=ohFfUluM7g4RsKou",
    "level": "B1-B2",
    "durationHours": 6,
    "videoCount": 38,
    "accent": "Irish",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-cfd2aeceef",
    "title": "Instant English",
    "url": "https://youtube.com/playlist?list=PLHbgDxFKMMS0SHFTejkbv6_I0UKqDE5Fm&si=hT6zvg15OB13Rkgf",
    "level": "B1-B2",
    "durationHours": 6,
    "videoCount": 33,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-0262B1-B2b308",
    "title": "American Culture",
    "url": "https://youtube.com/playlist?list=PLKxFPyhwH5ajBmB2hTUT8CQpgvbLj8wV-&si=FV-4SjMsSFGsRzJa",
    "level": "B1-B2",
    "durationHours": 6,
    "videoCount": 43,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-9b9b7bd721",
    "title": "Slow English With Brian",
    "url": "https://www.youtube.com/playlist?list=PL_m_LH-e5q4iyDg9vCAVxqye3_Mylp4dM",
    "level": "B1-B2",
    "durationHours": 6,
    "videoCount": 22,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-18b91422ef",
    "title": "Everyday English SLOW ENGLISH",
    "url": "https://www.youtube.com/playlist?list=PLrr_7ZHoCB21i6ToJ7HwDSzxv4tIuBlUW",
    "level": "B1-B2",
    "durationHours": 6,
    "videoCount": 30,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-af6bfaf590",
    "title": "American English With Brent (American culture)",
    "url": "https://www.youtube.com/playlist?list=PLZJxW7kBsjp_pIZ8W_Je8j3yGjxWV5YHe",
    "level": "B1-B2",
    "durationHours": 6,
    "videoCount": 31,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-c68a69fd6f",
    "title": "English Teacher Neo",
    "url": "https://www.youtube.com/playlist?list=PLDVXCKWFKmuKYSgFoJ0OKF-SULCueOkaq",
    "level": "B1-B2",
    "durationHours": 6,
    "videoCount": 14,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-6269dba277",
    "title": "Miss Honey (B1-B2)",
    "url": "https://youtube.com/playlist?list=PL8f0I_2tet-dz08Guo86B2auEenEMY05D&si=mIWCy55_zn_BpcnK",
    "level": "B1-B2",
    "durationHours": 5,
    "videoCount": 27,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-db9420d600",
    "title": "Legends, Myths and Stories",
    "url": "https://www.youtube.com/playlist?list=PL0J8XtnnCuENJQtCKVyNA4NaNY9GBqLNW",
    "level": "B1-B2",
    "durationHours": 5,
    "videoCount": 17,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-c3533d81a1",
    "title": "People, Places and Travel",
    "url": "https://www.youtube.com/playlist?list=PL0J8XtnnCuEP9-woyyqJpvclKGX4Z9bEn",
    "level": "B1-B2",
    "durationHours": 5,
    "videoCount": 18,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-2b64a2be15",
    "title": "Gusactiva",
    "url": "https://youtube.com/playlist?list=PL3g-xIeN3IdviIJfxcrsFw1GlZ7ZVVTIg&si=20xc94ig_VDLsjjE",
    "level": "B1-B2",
    "durationHours": 5,
    "videoCount": 32,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-975ff6f6d7",
    "title": "Learn English with Comics 1",
    "url": "https://youtube.com/playlist?list=PL7yrVR1epvJpdQ4c07GCrefXBviMJeDL7&si=jf7NW-PnIk5-ev6l",
    "level": "B1-B2",
    "durationHours": 5,
    "videoCount": 14,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-f21f8fc517",
    "title": "Learn English with Comics 2",
    "url": "https://youtube.com/playlist?list=PL7yrVR1epvJoNtK0qGM7yycvsgD7LQJpQ&si=mQcoQxU4iIPj4EqY",
    "level": "B1-B2",
    "durationHours": 5,
    "videoCount": 17,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-f07ea35900",
    "title": "Learn English with Comics 3",
    "url": "https://youtube.com/playlist?list=PL7yrVR1epvJq5EYial4Fo4eEEf4MeHjvN&si=HKjvmAV-lyOBRFEE",
    "level": "B1-B2",
    "durationHours": 5,
    "videoCount": 16,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-94a1f3eee8",
    "title": "PAPI English (Travel Vlogs)",
    "url": "https://youtube.com/playlist?list=PLIVKwmOySwdf1Rw7fAqPy-DzBq5SUbCDx&si=8iNvCqAVhbjctuXJ",
    "level": "B1-B2",
    "durationHours": 5,
    "videoCount": 41,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-6197fd2ee2",
    "title": "Fingtam English",
    "url": "https://youtube.com/playlist?list=PL5QKY42gcQzmf6xV-FEAhb1gF3Sx1eKUt&si=lO-ypxPu1KD1NsEg",
    "level": "B1-B2",
    "durationHours": 4,
    "videoCount": 20,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-c138bdc440",
    "title": "ComprehensibleInputAus",
    "url": "https://youtube.com/playlist?list=PLPCDGFknL8Ot2fCuYMS7c0WgY4rP32LlH&si=CZ1T2o5Tgvws2_C5",
    "level": "B1-B2",
    "durationHours": 4,
    "videoCount": 20,
    "accent": "Australian",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-e19a14984f",
    "title": "Miss Honey (B1-B2)",
    "url": "https://youtube.com/playlist?list=PL8f0I_2tet-d6uD3nVSpUoorMP0OUlGPE&si=YgW9FcR8CzeOTmvS",
    "level": "B1-B2",
    "durationHours": 4,
    "videoCount": 20,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-a0fB1-B24e36c",
    "title": "Isaac Cloward",
    "url": "https://youtube.com/playlist?list=PLKt7dWUJknRj2eI3IuVPdyqDvlal7zwAo&si=aRkgk-k1NZpbyXB4",
    "level": "B1-B2",
    "durationHours": 4,
    "videoCount": 19,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-098263637c",
    "title": "Everyday Australian English with Lauren",
    "url": "https://www.youtube.com/playlist?list=PLEZFal6VaZpjfwbBVbH16rToicwdj6w57",
    "level": "B1-B2",
    "durationHours": 7,
    "videoCount": 27,
    "accent": "Australian",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-99239886e5",
    "title": "English with Gemma Vlogs",
    "url": "https://youtube.com/playlist?list=PLcPAwtW6mYOjLvnfSuHgwjUPc2gkwvduR&si=WAbR8ET4u_W3XML5",
    "level": "B1-B2",
    "durationHours": 4,
    "videoCount": 17,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-1e1d30139b",
    "title": "Smashing English",
    "url": "https://youtube.com/playlist?list=PLQTHlq9H9JG6I4B8obubk8EO32nQoFnj6&si=yvFPfYJtG_4Lp6XJ",
    "level": "B1-B2",
    "durationHours": 4,
    "videoCount": 10,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-ebdc9c10ce",
    "title": "Level Up Your English w/ Nick",
    "url": "https://www.youtube.com/@LevelUpYourEnglishWithNick/videos",
    "level": "B1-B2",
    "durationHours": 4,
    "videoCount": 17,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-90b81e204a",
    "title": "Acquirable English",
    "url": "https://youtube.com/playlist?list=PL_pzbjRF59WQCCnKMn00c5_13qFR6fStF&si=Jl8r3G-iit3EB5XK",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 19,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-ec97778c03",
    "title": "English on the move 1",
    "url": "https://youtube.com/playlist?list=PL_EwrgAkRjGZ9k7Dce88z1FrLriiSfsdY&si=_gAWedWb-ZaFc6NF",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 11,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-779c23ec0d",
    "title": "Europe (excl. UK/Ireland)",
    "url": "https://www.youtube.com/playlist?list=PL0J8XtnnCuEOg3ThkVZYAaigdv4vaySER",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 10,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-cafd16fcb4",
    "title": "English with teacher Levi",
    "url": "https://youtube.com/playlist?list=PL_GLmQYdj60dDlvatriHBgPfcDnmP6zae&si=6Kvub6uD9TKN58t5",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 16,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-58afca113d",
    "title": "English on Autopilot",
    "url": "https://youtube.com/playlist?list=PLUCskyzT0rc7w8S71oh0u1DDcOR2YhsOT&si=0IdD4OkVqYzSdv-2",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 12,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-2fedb99c45",
    "title": "Sprout English",
    "url": "https://youtube.com/@sprout-english-language?si=lFNpz3BPJEI9E0ta",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 13,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-23de7141f5",
    "title": "English from the Ground Up",
    "url": "https://youtube.com/playlist?list=PLEeZEYCefqtgFkUGBQeihwGV76RlmZLZr&si=DKYxSF7YSFroVQgj",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 12,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-b9cd0e794a",
    "title": "Jayden Lamb",
    "url": "https://www.youtube.com/playlist?list=PL40_4A-5sz8ZwpTjhA7sglup30JG2d5Tn",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 29,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-cd7a5bc66f",
    "title": "English with Brittany",
    "url": "https://www.youtube.com/playlist?list=PL8a4iF7XlTBTzsk3llQ7nwlf1Tw2d_OAl",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 18,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-778b4411cf",
    "title": "English Learning Adventures",
    "url": "https://youtube.com/playlist?list=PLQQSV8gKWcVlubXP41x9mA_X-5lfN27ZU&si=-Jpuzti7l88i8dlO",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 16,
    "accent": "Canadian",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-4c7515193d",
    "title": "Input English in the kitchen",
    "url": "https://youtube.com/playlist?list=PL7fmP24ymbEvTiezeIh8VWxtxUklhLmn6&si=11Djnvs-LqvwdHE4",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 10,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-38c8f1b424",
    "title": "Input English Exploring Vlogs",
    "url": "https://youtube.com/playlist?list=PL7fmP24ymbEsnKIv0mD5b1uWaIzn810fu&si=9wF7Uu3H-7BDHBDx",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 10,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-ac0d028d00",
    "title": "Not Your Mother’s Eng (B1-B2)",
    "url": "https://youtube.com/playlist?list=PLMkT-IVAR40mylUEa27o4hvNNnh9XMdzX&si=wmWa6si6LVXO7Zcc",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 9,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-5b50c1106f",
    "title": "English on the move 2",
    "url": "https://youtube.com/playlist?list=PL_EwrgAkRjGaRqhtb_yuH_05-yFTbGcYc&si=uxYYV9CS4g5UAJyi",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 13,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-d5ab0c55B1-B2",
    "title": "English Input",
    "url": "https://youtube.com/playlist?list=PLmB90xqDKIbhNLBeZ0nKoPc8c6WHguAVj&si=YQu6rr2MskSbBRh-",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 20,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-0f0869cc72",
    "title": "English Input 2",
    "url": "https://youtube.com/playlist?list=PLmB90xqDKIbhRj-3IIZzMyc11iHAfcvsm&si=0YXHUpErQYfvXqw0",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 15,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-d38265738c",
    "title": "American Holidays",
    "url": "https://youtube.com/playlist?list=PLKxFPyhwH5ajR7uxaT20JS7bDIG9f5pjF&si=lLOVhCsuPiWjDga2",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 12,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-4c40cba472",
    "title": "American Traditions",
    "url": "https://youtube.com/playlist?list=PLKxFPyhwH5ahXXUOH4yjf430HQafA2udC&si=o2yQYwz6r5yugcKm",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 13,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-10b5b81403",
    "title": "Wicked Good English",
    "url": "https://youtube.com/playlist?list=PLSBUgMc0ndGcqtt01eWyiHtQZYS16BCX5&si=zqny4xMp4Ciczj4U",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 11,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-c788ce6404",
    "title": "Aussie English with Steph",
    "url": "https://www.youtube.com/playlist?list=PLBnbahcEQNUR37Gni7xOyFTwBdS_nkegV",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 13,
    "accent": "Australian",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-26d4ea043f",
    "title": "My English Coach Dave Vlogs",
    "url": "https://www.youtube.com/playlist?list=PL3fc304Ni5lEH3w7-StT7O1e3vkgJm11O",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 3,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-ff2467db36",
    "title": "English with Lewis",
    "url": "https://www.youtube.com/playlist?list=PLXX2gkl4aNsa7Dd9CRbdE48VVQHftrbFb",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 12,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-3cc149f259",
    "title": "English Like Mike",
    "url": "https://www.youtube.com/@EnglishLikeMike",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 13,
    "accent": "Australian",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-7461d35fb0",
    "title": "English with Evie",
    "url": "https://youtube.com/@englishwithevie?si=UvHjVfoZW2qW2f7z",
    "level": "B1-B2",
    "durationHours": 4,
    "videoCount": 27,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-374931d1e2",
    "title": "Fin Teaches English",
    "url": "https://youtube.com/playlist?list=PLmMTxW0t-jbbh1qZFtzBNZPrWN1OQD0SY&si=SjAdSm8VDLZOxSkT",
    "level": "B1-B2",
    "durationHours": 5,
    "videoCount": 24,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-bd1717918b",
    "title": "North and South America",
    "url": "https://www.youtube.com/playlist?list=PL0J8XtnnCuEOujeOJdJ9LcmjTrltsuWDe",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 10,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-b58f1db4c0",
    "title": "English Anywhere",
    "url": "https://www.youtube.com/@english4u-s5r",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 6,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-bc5d035a8d",
    "title": "American English With Brent (New York City English Lessons)",
    "url": "https://www.youtube.com/playlist?list=PLZJxW7kBsjp_BfPLG2_0Rrqa0ixVheVen",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 7,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-96be55b429",
    "title": "Not Your Mother’s Eng (B1-B2)",
    "url": "https://youtube.com/playlist?list=PLMkT-IVAR40k2g_UmYNf-gOccqLKOnCWI&si=-tlAlKx7SsqVxodQ",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 5,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-be1ebed307",
    "title": "English Comprehensible Input",
    "url": "https://youtube.com/playlist?list=PL95nNa6WM9n-3GjgHxWmCl9ODwDqKVPhp&si=JTcjwif-H1a7pD-G",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 3,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-ffbf949B1-B29",
    "title": "Learn English Vlogs",
    "url": "https://youtube.com/playlist?list=PLQTHlq9H9JG4OyaAqjuL6txwoZx2Mj3ra&si=SlPl19N6yCJtRKC6",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 11,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-1f185d0bf2",
    "title": "Easy English Vlogs for Learners",
    "url": "https://www.youtube.com/playlist?list=PLu1As8p-8QYcqNVunAMMlGkOEaD1OWavg",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 11,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-89fd4cd2e1",
    "title": "Tyler's Real Life English",
    "url": "https://www.youtube.com/playlist?list=PL1qPAFgOS5i4pOkVPTTW_WJH1by2Py8sG",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 9,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-8ea0f037f3",
    "title": "English is EZ with Connor",
    "url": "https://www.youtube.com/playlist?list=PLYaLdgNAMCnk8Dx9WRi_5BQR_L32V9qYV",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 3,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-03a2dd71b7",
    "title": "My English Coach Dave",
    "url": "https://www.youtube.com/playlist?list=PL3fc304Ni5lHUmQfTuqrPxx5ro22Y2npT",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 4,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-467b7e29f8",
    "title": "English Comprehensible Input by Isaac Cloward",
    "url": "https://www.youtube.com/playlist?list=PLKt7dWUJknRjKnnIv2IyVXW-MpVS-vVr3",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 5,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-c2857e79b8",
    "title": "Outstanding English",
    "url": "https://youtube.com/playlist?list=PLjfEpqkZSEyjm6Q2H5PrM6XrZRPmmm1fz&si=_mpgPhqQUEW6M76R",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 13,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-71cdB1-B2e002",
    "title": "Learn English with Talon",
    "url": "https://youtube.com/playlist?list=PLCyxbdBiP89dVs_DD4ijhrHjSzVHW49j0&si=b_s5n9BDEDUfW0fA",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 7,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-bf8c3fc5fe",
    "title": "Englishteacherdowsett",
    "url": "https://youtube.com/playlist?list=PLoWIvJAIRjBLibbn4TBdckHsbXV-9RXpo&si=E4AbPAI5wToNVBzN",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 6,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
  {
    "id": "pl-85edb7c43f",
    "title": "English with Eleanor",
    "url": "https://youtube.com/playlist?list=PLjMJqGrasrCEzvOpyaAtXDJ4Prc5kZG8_&si=ar5EnjByk7HurpSq",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 39,
    "accent": "Irish",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": null
  },
   {
    "id": "pl-a826eec48c",
    "title": "Thinking English Gaming",
    "url": "https://youtube.com/@thinking-english-gaming",
    "level": "B1-B2",
    "durationHours": 0,
    "videoCount": 24,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-cbf58028b1",
    "title": "English Easy Mode",
    "url": "https://youtube.com/@englisheasymode",
    "level": "B1-B2",
    "durationHours": 0,
    "videoCount": 13,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-f993f390c4",
    "title": "Learn with Wavey",
    "url": "https://youtube.com/@learnwithwavey",
    "level": "A2",
    "durationHours": 2,
    "videoCount": 5,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-13ae1901d0",
    "title": "Walk With Me English",
    "url": "https://www.youtube.com/playlist?list=PLzkcVPMKc9thq6Cyf0EY9Z-MDRLTcMvyN",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 10,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-3d6be787e9",
    "title": "English with Jason",
    "url": "https://youtube.com/@english_with_jason",
    "level": "B1-B2",
    "durationHours": 3,
    "videoCount": 8,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-ab23f7360c",
    "title": "EEEnglish Official",
    "url": "https://youtube.com/@eeenglish.official",
    "level": "A2",
    "durationHours": 2,
    "videoCount": 26,
    "accent": "Canadian",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-c067cc197a",
    "title": "Jeff Cole English",
    "url": "https://youtube.com/@jeffcoleenglish",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 4,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-60697f951e",
    "title": "Natural English with Ed",
    "url": "https://youtube.com/@naturalenglishwithed",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 8,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-2960192b63",
    "title": "Conversations with Kristin",
    "url": "https://youtube.com/@conversationswithkristin",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 10,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-ed2d26fbac",
    "title": "Learn English With Famous Stories - Easy English Listening Playlist",
    "url": "https://www.youtube.com/playlist?list=PL37fr9hk1cIEh9LXPg-xyzPt7sHVrR-Iv",
    "level": "B1-B2",
    "durationHours": 6,
    "videoCount": 30,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-b8842236c5",
    "title": "Its English Time with Victoria",
    "url": "https://youtube.com/@itsenglishtimewithvictoria",
    "level": "B1-B2",
    "durationHours": 0,
    "videoCount": 5,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-cee8d09f7a",
    "title": "Super Mario Odyssey",
    "url": "https://www.youtube.com/playlist?list=PLEeZEYCefqtgkklLILZR4zA2nH30B_Yt0",
    "level": "B1-B2",
    "durationHours": 9,
    "videoCount": 7,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-8e74210939",
    "title": "Learn English with Terraria",
    "url": "https://www.youtube.com/playlist?list=PLEeZEYCefqthiuHQuuB7WYro9ejvsEm-A",
    "level": "A2",
    "durationHours": 1,
    "videoCount": 3,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-d226c6cf27",
    "title": "Learn English with Minecraft!",
    "url": "https://www.youtube.com/playlist?list=PLi2edHIB6iaoD1W_Ae19wW0fWD3Te7-Fk",
    "level": "B1-B2",
    "durationHours": 6,
    "videoCount": 14,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-1ff9dec7ab",
    "title": "Learn English with Overcooked 2!",
    "url": "https://www.youtube.com/playlist?list=PLi2edHIB6iapZyJQ9Xy6Dc-TO9M6g_B2H",
    "level": "B1-B2",
    "durationHours": 4,
    "videoCount": 12,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-ea0e64c10f",
    "title": "Learn English with Astro Bot!",
    "url": "https://www.youtube.com/playlist?list=PLi2edHIB6iaoxZ_FEC4i3fhaP3-4EDWCE",
    "level": "B1-B2",
    "durationHours": 14,
    "videoCount": 37,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-5fe05cf445",
    "title": "Learn English with The Plucky Squire!",
    "url": "https://www.youtube.com/playlist?list=PLi2edHIB6iaq9wZ1Pd0PnGYw-IAQITKL_",
    "level": "B1-B2",
    "durationHours": 8,
    "videoCount": 19,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-d356e82190",
    "title": "Beginner English with Comfy Corners!",
    "url": "https://www.youtube.com/playlist?list=PLi2edHIB6iaoGDBfBdTfNhD5iJIQpZ2TL",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 4,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-cd3b1b68d6",
    "title": "Learn English with Goat Simulator 3!",
    "url": "https://www.youtube.com/playlist?list=PLi2edHIB6iaoxw1jOpeME34UObUhfsCv7",
    "level": "B1-B2",
    "durationHours": 5,
    "videoCount": 13,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-d5a30a42e2",
    "title": "Let's Play and Learn English with Stardew Valley",
    "url": "https://www.youtube.com/playlist?list=PLrTDQeZKq5TtHQ-MWZdecCheSnp44U6nT",
    "level": "A2",
    "durationHours": 2,
    "videoCount": 8,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-bc19b6c7cf",
    "title": "Easy English Short Stories",
    "url": "https://www.youtube.com/playlist?list=PLBHhtT27aGKWT0saFuFn6T4H8V4UV2JaM",
    "level": "A1",
    "durationHours": 2,
    "videoCount": 27,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-481b88dc36",
    "title": "Easy Stories in English",
    "url": "https://www.youtube.com/@easystoriesinenglish/videos",
    "level": "B1-B2",
    "durationHours": 0,
    "videoCount": 269,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-ecfb061a5f",
    "title": "Look and Learn English",
    "url": "https://www.youtube.com/@LookandLearnEnglish/videos",
    "level": "A2",
    "durationHours": 0,
    "videoCount": 46,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-245f139f21",
    "title": "Slow Easy English",
    "url": "https://www.youtube.com/playlist?list=PLUiFeF9KuaPabTQ1HEZ3pvD-JkiiqZRu9",
    "level": "A2",
    "durationHours": 1,
    "videoCount": 7,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-b5bd979643",
    "title": "Easy British English Vlogs",
    "url": "https://www.youtube.com/playlist?list=PLUiFeF9KuaPZv3z0t67PIPO-mOrggJa3Q",
    "level": "A2",
    "durationHours": 2,
    "videoCount": 6,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-68ee92fb62",
    "title": "Learn English with Real Everyday Conversations",
    "url": "https://www.youtube.com/playlist?list=PLUiFeF9KuaPZiJqP0dcYoCvZ3dgUYcts2",
    "level": "B1-B2",
    "durationHours": 2,
    "videoCount": 14,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": null,
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-aab7ee90db",
    "title": "The Easy English",
    "url": "https://www.youtube.com/playlist?list=PLUiFeF9KuaPYmR2weCDV2zCrrSEnP7p71",
    "level": "B1-B2",
    "durationHours": 5,
    "videoCount": 16,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-65639a8961",
    "title": "Daily Dose of English with Ben",
    "url": "https://www.youtube.com/playlist?list=PL7yrVR1epvJomekOmbKGT_RJcUAjchxjm",
    "level": "B1-B2",
    "durationHours": 43,
    "videoCount": 229,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-b8879b4e2b",
    "title": "A1 English Listening Practice",
    "url": "https://www.youtube.com/playlist?list=PLhNRdHEdUQewzYZ0X6gt3x9_CVen_HldI",
    "level": "A1",
    "durationHours": 11,
    "videoCount": 62,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-f6021da812",
    "title": "A2 English Listening Practice",
    "url": "https://www.youtube.com/playlist?list=PLhNRdHEdUQexUblCTMd1ATwOd5J4SxtNM",
    "level": "A2",
    "durationHours": 10,
    "videoCount": 59,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-c64c922372",
    "title": "B1 English Listening Practice",
    "url": "https://www.youtube.com/playlist?list=PLhNRdHEdUQeyIjNRrwWnMU_iph8amkaJg",
    "level": "B1-B2",
    "durationHours": 9,
    "videoCount": 47,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-6d8a024060",
    "title": "VOA Learning English",
    "url": "https://www.youtube.com/playlist?list=PLd9hCvj34W5hZxGsu5etKF6bZ9w4Ap2hl",
    "level": "B1-B2",
    "durationHours": 170,
    "videoCount": 346,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-294934be61",
    "title": "Jack Redfold Learn English Vocabulary",
    "url": "https://www.youtube.com/playlist?list=PLfMCWbgeioA0voaIYe0HHAP5zM14e143F",
    "level": "B1-B2",
    "durationHours": 7,
    "videoCount": 29,
    "accent": "British",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-b897f2a3b4",
    "title": "Who is Rachel of Rachel's English?",
    "url": "https://www.youtube.com/playlist?list=PLrqHrGoMJdTT5qCzkqlUtiopui2irMGOn",
    "level": "B1-B2",
    "durationHours": 13,
    "videoCount": 25,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-27a6e4417f",
    "title": "English Listening Comprehension for Advanced Learners",
    "url": "https://www.youtube.com/playlist?list=PL5bLw9Uguvv0Q6yEZUcNMs0uQDYpffIx4",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 30,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-1c294426ac",
    "title": "English Listening Comprehension for Intermediate Learners",
    "url": "https://www.youtube.com/playlist?list=PL5bLw9Uguvv1VRVl3gHBt-FcM__k3UY9L",
    "level": "B1-B2",
    "durationHours": 1,
    "videoCount": 30,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-d1a6fd9a67",
    "title": "English Listening Comprehension for Beginners",
    "url": "https://www.youtube.com/playlist?list=PL5bLw9Uguvv3Mjnzd0YGmu-lGRWRWv-cU",
    "level": "A2",
    "durationHours": 1,
    "videoCount": 28,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
    "id": "pl-bb6d5e20cb",
    "title": "English Listening Comprehension for Absolute Beginners",
    "url": "https://www.youtube.com/playlist?list=PL5bLw9Uguvv11fx6bS68yK5OeXAqLU3mW",
    "level": "A1",
    "durationHours": 1,
    "videoCount": 29,
    "accent": "American",
    "avatar": "",
    "notes": "",
    "format": "podcast",
    "addedAt": "2026-07-28"
  },
  {
  "id": "pl-ba147b1b7e",
  "title": "Jacob Hadleys",
  "url": "https://www.youtube.com/@jacobhadleys",
  "level": "B1-B2",
  "durationHours": 1,
  "videoCount": 7,
  "accent": "American",
  "avatar": "",
  "notes": "",
  "format": null,
  "addedAt": "2026-07-31"
},
{
  "id": "pl-b0aad94005",
  "title": "English with Patrick",
  "url": "https://www.youtube.com/playlist?list=PLSoXr9oG6rxw",
  "level": "A2",
  "durationHours": 0,
  "videoCount": 2,
  "accent": "American",
  "avatar": "",
  "notes": "",
  "format": null,
  "addedAt": "2026-07-31"
},
{
  "id": "pl-e46c91f517",
  "title": "English Comprehensible Input (A2)",
  "url": "https://www.youtube.com/playlist?list=PLGQI8pM4Rl1CJPSKidA9QDSX6EycbjvZX",
  "level": "A2",
  "durationHours": 1,
  "videoCount": 6,
  "accent": "British",
  "avatar": "",
  "notes": "",
  "format": null,
  "addedAt": "2026-07-31"
},
{
  "id": "pl-6c3630c17c",
  "title": "English Comprehensible Input (A1)",
  "url": "https://www.youtube.com/playlist?list=PLGQI8pM4Rl1AUj1GK9wJbuDnx_XuIrB4X",
  "level": "A1",
  "durationHours": 0,
  "videoCount": 4,
  "accent": "British",
  "avatar": "",
  "notes": "",
  "format": null,
  "addedAt": "2026-07-31"
},
{
  "id": "pl-95582d90ad",
  "title": "Learn English with the Far Side",
  "url": "https://www.youtube.com/playlist?list=PLShoI-wSzPmM",
  "level": "A2",
  "durationHours": 0,
  "videoCount": 4,
  "accent": "American",
  "avatar": "",
  "notes": "",
  "format": null,
  "addedAt": "2026-07-31"
},
{
  "id": "pl-7156fe55e3",
  "title": "Learn English with the Animal Man",
  "url": "https://www.youtube.com/playlist?list=PLfwjZThbe7zs",
  "level": "A2",
  "durationHours": 1,
  "videoCount": 4,
  "accent": "American",
  "avatar": "",
  "notes": "",
  "format": null,
  "addedAt": "2026-07-31"
},
{
  "id": "pl-7f513510e4",
  "title": "Jay Fujiwara",
  "url": "https://www.youtube.com/@jayfujiwara",
  "level": "A2",
  "durationHours": 0,
  "videoCount": 1,
  "accent": "British",
  "avatar": "",
  "notes": "",
  "format": null,
  "addedAt": "2026-07-31"
},
{
  "id": "pl-1dea524244",
  "title": "English on the go",
  "url": "https://www.youtube.com/@englishonthegoyt",
  "level": "A2",
  "durationHours": 0,
  "videoCount": 1,
  "accent": "American",
  "avatar": "",
  "notes": "",
  "format": null,
  "addedAt": "2026-07-31"
},
{
  "id": "pl-958a1f1e32",
  "title": "British English Teacher Roy",
  "url": "https://www.youtube.com/playlist?list=PLWQAdypc0Pdw",
  "level": "B1-B2",
  "durationHours": 1,
  "videoCount": 2,
  "accent": "British",
  "avatar": "",
  "notes": "",
  "format": null,
  "addedAt": "2026-07-31"
},
{
  "id": "pl-98a1bd9069",
  "title": "Walk & Talk Videos",
  "url": "https://www.youtube.com/playlist?list=PLqVwPFqmUxaNsC-ypq_A1Qj0QGvzzyE7F",
  "level": "B1-B2",
  "durationHours": 10,
  "videoCount": 26,
  "accent": "British",
  "avatar": "",
  "notes": "",
  "format": null,
  "addedAt": "2026-07-31"
}
];
